#dnf install mysql-server -y
#
#systemctl enable mysqld
#systemctl restart mysqld
#
#mysql_secure_installation --set-root-pass RoboShop@1

- name: install mysql
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: enable mysqld
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: ret roboshop password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1