
- name: Create a user
  ansible.builtin.user:
    name: roboshop


- name: remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download and extract
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component_name }}-v3.zip
    dest: /app
    remote_src: yes