
- name: disable node default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable nodejs default version
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: app_prereq
  ansible.builtin.include_tasks:
    file: app-prereq.yml

- name: Installnpm dependencies
  community.general.npm:
    path: /app

- name: include systemd
  ansible.builtin.tasks:
    file: systemd.yml


